INSERT [dbo].[PhanCongGiangDay] ([NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES (2014, 2, 32, N'CT46', N'CTK34B')
INSERT [dbo].[PhanCongGiangDay] ([NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES (2014, 2, 33, N'CT60', N'CTK34A')
INSERT [dbo].[PhanCongGiangDay] ([NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES (2014, 2, 34, N'CT02', N'CTK34A')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES (2014, 2, 35, N'TN12', N'CTK34A')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES (2014, 2, 36, N'CT07', N'CTK34A')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES (2014, 2, 37, N'TN20', N'CTK34A')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES (2014, 2, 38, N'CT09', N'CTK34A')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES (2014, 2, 39, N'CT65', N'CTK34A')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 40, N'CT13', N'CTK34B')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 41, N'CT46', N'CTK34B')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 42, N'TH01', N'CTK34B')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 43, N'CT13', N'CTK34B')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 4, N'TN15', N'CTK34B')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 19, N'TN12', N'CTK35')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 20, N'CT46', N'CTK35')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 21, N'TN22', N'CTK35')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 22, N'CT13', N'CTK35')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 23, N'CT25', N'CTK35')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 24, N'TH01', N'CTK35')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 25, N'CT46', N'CTK35')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 26, N'CT28', N'CTK35')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES (2014, 2, 27, N'CT65', N'CTK35CD')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 29, N'TH01', N'CTK35CD')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 30, N'CT60', N'CTK35CD')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 17, N'TN15', N'CTK36')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 18, N'CT13', N'CTK36')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 11, N'CT59', N'CTK36CD')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 12, N'CT28', N'CTK36CD')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 13, N'CT03', N'CTK36CD')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 14, N'CT02', N'CTK36CD')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 16, N'CT07', N'CTK36CD')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 1, N'TN15', N'CTK37')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 2, N'TN16', N'CTK37')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 3, N'CT65', N'CTK37')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 31, N'CT60', N'CTK37')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 7, N'CT60', N'CTK37CD')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 8, N'CT13', N'CTK37CD')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 9, N'CT09', N'CTK37CD')
INSERT [dbo].[PhanCongGiangDay] ( [NamHoc], [HocKy], [MonHocId], [MaGv], [TenLop]) VALUES ( 2014, 2, 10, N'CT50', N'CTK37CD')